version: '3'
services:
  haaukins-exercises:
    container_name: haaukins-exercises
    env_file:
      - .env
    build: .
    ports:
      - 50095:50095
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - ${CERTS_PATH}:/certs:ro
      - ${CONFIG_PATH}:/config.yml:ro  # mount config file
    networks:
      - internal

  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - internal

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    restart: always
    ports:
      - "8081:8081"
    networks:
      - internal

volumes:
  data:

networks:
  internal:
    driver: bridge