version: '3'
services:
  haaukins-exercises:
    container_name: haaukins-exercises
#     env_file:
#       - .env
    build: .
    ports:
      - 9090:9090       #change them according the .env file
#     restart: on-failure
    depends_on:
      - mongo
    networks:
      - internal

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - mongo-data:/data/db     #change into host volume
    networks:
      - internal

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
    driver: bridge