name: Build and Publish Docker
on:
  push:
    tags:
      - 'v*.*.*' ## will be the tag of docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aaunetworksecurity/haaukins-exercises
          tag_with_ref: true
          tag_with_sha: true

      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: aau-network-security/haaukins-exercises/haau-exs-server
          tag_with_ref: true
          tag_with_sha: true